version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "349644152945"
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPO: "pulsocast-lambdas"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $IMAGE_URI

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $IMAGE_URI
      - echo Image pushed successfully - $IMAGE_URI
      - printf '{"ImageURI":"%s"}' $IMAGE_URI > imageDetail.json

artifacts:
  files:
    - imageDetail.json
